apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kf74glk8q-nodejs
  janus-idp.io/tekton: kf74glk8q-nodejs
  backstage.io/kubernetes-id: kf74glk8q-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kf74glk8q-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
